export const codingPracticesData = {
  python: [
    {
      id: "practice-python-1",
      title: "Coding Practice - 1",
      description: "Introduction to Python basic concepts",
      questions: [
        {
          id: "q-python-1-001",
          title: "Hello World",
          difficulty: "Easy",
          description: "Write a program that prints Hello World as output.",
          sampleInput: "",
          sampleOutput: "Hello World",
          testCases: [
            { input: "", output: "Hello World", visible: true },
            { input: "", output: "Hello World", visible: true },
            { input: "", output: "Hello World", visible: false },
            { input: "", output: "Hello World", visible: false },
            { input: "", output: "Hello World", visible: false },
          ],
          defaultCode: `print("Hello World")`,
          score: 5,
          status: "solved",
          attempts: [{ passed: 1, total: 1, score: 5 }],
        },
        {
          id: "q-python-1-002",
          title: "Three Hashes",
          difficulty: "Easy",
          description: "Write a program that prints three hashes (#) in separate lines.",
          sampleInput: "",
          sampleOutput: "#\n#\n#",
          testCases: [
            { input: "", output: "#\n#\n#", visible: true },
            { input: "", output: "#\n#\n#", visible: true },
            { input: "", output: "#\n#\n#", visible: false },
            { input: "", output: "#\n#\n#", visible: false },
            { input: "", output: "#\n#\n#", visible: false },
          ],
          defaultCode: `print("#")\nprint("#")\nprint("#")`,
          score: 5,
          status: "solved",
          attempts: [{ passed: 1, total: 1, score: 5 }],
        },
        {
          id: "q-python-1-003",
          title: "Simple Addition",
          difficulty: "Easy",
          description: "Write a program that takes two numbers as input and prints their sum.",
          sampleInput: "5\n3",
          sampleOutput: "8",
          testCases: [
            { input: "5\n3", output: "8", visible: true },
            { input: "10\n20", output: "30", visible: true },
            { input: "-5\n8", output: "3", visible: false },
            { input: "0\n0", output: "0", visible: false },
            { input: "100\n200", output: "300", visible: false },
          ],
          defaultCode: `num1 = int(input())\nnum2 = int(input())\nprint(num1 + num2)`,
          score: 5,
          status: "unsolved",
          attempts: [],
        },
      ],
    },
    {
      id: "practice-python-2",
      title: "Coding Practice - 2",
      description: "Variables and Data Types",
      questions: [
        {
          id: "q-python-2-001",
          title: "Variable Assignment",
          difficulty: "Easy",
          description: "Create a variable named 'message' and assign the string 'Python is fun!' to it, then print it.",
          sampleInput: "",
          sampleOutput: "Python is fun!",
          testCases: [
            { input: "", output: "Python is fun!", visible: true },
            { input: "", output: "Python is fun!", visible: true },
            { input: "", output: "Python is fun!", visible: false },
            { input: "", output: "Python is fun!", visible: false },
            { input: "", output: "Python is fun!", visible: false },
          ],
          defaultCode: `# Write your code here`,
          score: 5,
          status: "unsolved",
          attempts: [],
        },
        {
          id: "q-python-2-002",
          title: "Type Conversion",
          difficulty: "Medium",
          description: "Take a string input of a number, convert it to integer, add 10, and print the result.",
          sampleInput: "25",
          sampleOutput: "35",
          testCases: [
            { input: "25", output: "35", visible: true },
            { input: "100", output: "110", visible: true },
            { input: "0", output: "10", visible: false },
            { input: "-5", output: "5", visible: false },
            { input: "7", output: "17", visible: false },
          ],
          defaultCode: `# Write your code here`,
          score: 10,
          status: "unsolved",
          attempts: [],
        },
      ],
    },
    {
      id: "practice-python-3",
      title: "Coding Practice - 3",
      description: "Sequence of Instructions",
      questions: [
        {
          id: "q-python-3-001",
          title: "Simple Calculator",
          difficulty: "Medium",
          description: "Create a calculator that takes two numbers and an operator (+, -, *, /) and prints the result.",
          sampleInput: "10\n5\n*",
          sampleOutput: "50",
          testCases: [
            { input: "10\n5\n*", output: "50", visible: true },
            { input: "15\n3\n/", output: "5.0", visible: true },
            { input: "8\n3\n+", output: "11", visible: false },
            { input: "20\n4\n-", output: "16", visible: false },
            { input: "7\n2\n%", output: "1", visible: false },
          ],
          defaultCode: `# Write your code here`,
          score: 10,
          status: "unsolved",
          attempts: [],
        },
      ],
    },
  ],
  javascript: [
    {
      id: "practice-js-1",
      title: "JavaScript Practice - I",
      description: "Basic JavaScript concepts",
      questions: [
        {
          id: "q-js-1-001",
          title: "Hello JavaScript",
          difficulty: "Easy",
          description: "Write a function that returns 'Hello JavaScript'",
          sampleInput: "",
          sampleOutput: "Hello JavaScript",
          testCases: [
            { input: "", output: "Hello JavaScript", visible: true },
            { input: "", output: "Hello JavaScript", visible: true },
            { input: "", output: "Hello JavaScript", visible: false },
          ],
          defaultCode: `function hello() {\n  // Write your code here\n}`,
          score: 5,
          status: "unsolved",
          attempts: [],
        },
      ],
    },
  ],
}
