export const codingPracticesData = {
  python: [
    {
      id: "practice-python-1",
      title: "Coding Practice - 1",
      description: "Introduction to Python basic concepts",
      questions: [
        {
          id: "q-python-1-001",
          title: "Hello World",
          difficulty: "Easy",
          description: "Write a program that prints Hello World as output.",
          sampleInput: "Hello World",
          sampleOutput: "Hello World",
          testCases: [
            { input: "Hello World", output: "Hello World", visible: true },
          ],
          defaultCode: ``,
          score: 5,
          status: "unsolved",
          attempts: [],
        },
        {
          id: "q-python-1-002",
          title: "Three Hashes",
          difficulty: "Easy",
          description:
            "Write a program that prints three hashes (#) in separate lines.",
          sampleInput: "###",
          sampleOutput: "###",
          testCases: [{ input: "###", output: "###", visible: true }],
          defaultCode: ``,
          score: 5,
          status: "unsolved",
          attempts: [],
        },
        {
          id: "q-python-1-003",
          title: "Simple Addition",
          difficulty: "Easy",
          description:
            "Write a program that takes two numbers as input and prints their sum.",
          sampleInput: "5\n3",
          sampleOutput: "8",
          testCases: [
            { input: "5\n3", output: "8", visible: true },
            { input: "10\n20", output: "30", visible: true },
            { input: "-5\n8", output: "3", visible: false },
            { input: "0\n0", output: "0", visible: false },
            { input: "100\n200", output: "300", visible: false },
          ],
          defaultCode: ``,
          score: 5,
          status: "unsolved",
          attempts: [],
        },
      ],
    },
    {
      id: "practice-python-2",
      title: "Coding Practice - 2",
      description: "Variables and Data Types",
      questions: [
        {
          id: "q-python-2-001",
          title: "Sum of 2495 and 789358",
          difficulty: "Easy",
          description:
            "Write a program that prints two numbers, 2495 and 789358",
          sampleInput: "",
          sampleOutput: "791853",
          testCases: [
            {
              input: "",
              output: "",
              visible: true,
            },
          ],
          defaultCode: ``,
          score: 5,
          status: "unsolved",
          attempts: [],
        },
        {
          id: "q-python-2-002",
          title: "Type Conversion",
          difficulty: "Easy",
          description: "Subtract 596 from 193856",
          sampleInput: "",
          sampleOutput: "193260",
          testCases: [{ input: "", output: "", visible: true }],
          defaultCode: ``,
          score: 5,
          status: "unsolved",
          attempts: [],
        },
      ],
    },
    {
      id: "practice-python-3",
      title: "Coding Practice - 3",
      description: "Sequence of Instructions",
      questions: [
        {
          id: "q-python-3-001",
          title: "Product of 37, 61 and 391",
          difficulty: "Medium",
          description:
            "Write a program that prints the product of three numbers, 37, 61, and 391",
          sampleInput: "",
          sampleOutput: "882487",
          testCases: [{ input: "", output: "882487", visible: true }],
          defaultCode: ``,
          score: 10,
          status: "unsolved",
          attempts: [],
        },
      ],
    },
  ],

  javascript: [
    {
      id: "practice-js-1",
      title: "Coding Practice - 1",
      description: "Introduction to JavaScript basics",
      questions: [
        {
          id: "q-js-1-001",
          title: "Hello JavaScript",
          difficulty: "Easy",
          description: "Write a function that returns 'Hello JavaScript'.",
          sampleInput: "",
          sampleOutput: "Hello JavaScript",
          testCases: [{ input: "", output: "Hello JavaScript", visible: true }],
          defaultCode: ``,
          score: 5,
          status: "unsolved",
          attempts: [],
        },
        {
          id: "q-js-1-002",
          title: "Sum of Two Numbers",
          difficulty: "Easy",
          description:
            "Write a function that takes two numbers and returns their sum.",
          sampleInput: "5\n3",
          sampleOutput: "8",
          testCases: [
            { input: "5\n3", output: "8", visible: true },
            { input: "10\n20", output: "30", visible: true },
            { input: "-5\n8", output: "3", visible: false },
          ],
          defaultCode: ``,
          score: 5,
          status: "unsolved",
          attempts: [],
        },
      ],
    },
  ],
};
