// src/Python/Loops/ForLoop_MCQ.js
import React, { useState, useEffect } from "react";
import { useAuth } from "../../context/AuthContext";

import MCQLogic from "../../SubtopicsPage/MCQLogic";
import { CodeBlock } from "../../CodeOutputBlocks";

const questionsData = [
  {
    question: (
      <div>
        <p>What will be the exact output?</p>
        <CodeBlock
          language="python"
          code={`for i in range(4):\n    print(i)`}
        />
      </div>
    ),
    options: [
      <span>
        0<br />1<br />2<br />3<br />4
      </span>,
      <span>
        0<br />1<br />2<br />3
      </span>,
      <span>
        1<br />2<br />3<br />4
      </span>,
      <span>Nothing prints</span>,
    ],
    answer: (
      <span>
        0<br />1<br />2<br />3
      </span>
    ),
  },

  {
    question: (
      <div>
        <p>What prints one character per line?</p>
        <CodeBlock
          language="python"
          code={`for ch in "CODE":\n    print(ch)`}
        />
      </div>
    ),
    options: [
      <span>CODE</span>,
      <span>C O D E</span>,
      <span>
        C<br />O<br />D<br />E
      </span>,
      <span>Error</span>,
    ],
    answer: (
      <span>
        C<br />O<br />D<br />E
      </span>
    ),
  },

  {
    question: (
      <div>
        <p>Predict the output carefully:</p>
        <CodeBlock
          language="python"
          code={`for num in range(3, 7):\n    print(num)`}
        />
      </div>
    ),
    options: [
      <span>
        3<br />4<br />5<br />6<br />7
      </span>,
      <span>
        3<br />4<br />5<br />6
      </span>,
      <span>
        4<br />5<br />6<br />7
      </span>,
      <span>
        0<br />1<br />2<br />3
      </span>,
    ],
    answer: (
      <span>
        3<br />4<br />5<br />6
      </span>
    ),
  },

  {
    question: (
      <div>
        <p>How many times will "Hi" be printed?</p>
        <CodeBlock
          language="python"
          code={`for i in range(5):\n    print("Hi")`}
        />
      </div>
    ),
    options: [
      <span>
        Hi
        <br />
        Hi
        <br />
        Hi
        <br />
        Hi
        <br />
        Hi
      </span>,
      <span>Hi Hi Hi Hi Hi</span>,
      <span>
        Hi
        <br />
        Hi
        <br />
        Hi
        <br />
        Hi
      </span>,
      <span>5</span>,
    ],
    answer: (
      <span>
        Hi
        <br />
        Hi
        <br />
        Hi
        <br />
        Hi
        <br />
        Hi
      </span>
    ),
  },

  {
    question: (
      <div>
        <p>What numbers will be printed?</p>
        <CodeBlock
          language="python"
          code={`for x in range(2, 10, 3):\n    print(x)`}
        />
      </div>
    ),
    options: [
      <span>
        2<br />5<br />8
      </span>,
      <span>
        2<br />5<br />8<br />
        11
      </span>,
      <span>
        3<br />6<br />9
      </span>,
      <span>
        2<br />4<br />6<br />8
      </span>,
    ],
    answer: (
      <span>
        2<br />5<br />8
      </span>
    ),
  },

  {
    question: (
      <div>
        <p>Observe this string loop output:</p>
        <CodeBlock
          language="python"
          code={`text = "HELLO"\nfor letter in text:\n    print(letter)`}
        />
      </div>
    ),
    options: [
      <span>HELLO</span>,
      <span>H E L L O</span>,
      <span>
        H<br />E<br />L<br />L<br />O
      </span>,
      <span>Error</span>,
    ],
    answer: (
      <span>
        H<br />E<br />L<br />L<br />O
      </span>
    ),
  },

  {
    question: (
      <div>
        <p>What is the exact output?</p>
        <CodeBlock
          language="python"
          code={`for i in range(1, 6):\n    print(i * 3)`}
        />
      </div>
    ),
    options: [
      <span>
        3<br />6<br />9<br />
        12
        <br />
        15
      </span>,
      <span>
        1<br />2<br />3<br />4<br />5
      </span>,
      <span>
        0<br />3<br />6<br />9<br />
        12
      </span>,
      <span>
        3<br />6<br />9<br />
        12
      </span>,
    ],
    answer: (
      <span>
        3<br />6<br />9<br />
        12
        <br />
        15
      </span>
    ),
  },

  {
    question: (
      <div>
        <p>How many numbers are generated by range(8)?</p>
        <CodeBlock
          language="python"
          code={`for n in range(8):\n    print(n)`}
        />
      </div>
    ),
    options: [
      <span>8 numbers (0 to 7)</span>,
      <span>9 numbers (0 to 8)</span>,
      <span>7 numbers (1 to 7)</span>,
      <span>Infinite</span>,
    ],
    answer: <span>8 numbers (0 to 7)</span>,
  },

  {
    question: (
      <div>
        <p>What will be printed?</p>
        <CodeBlock
          language="python"
          code={`for i in range(10, 5, -1):\n    print(i)`}
        />
      </div>
    ),
    options: [
      <span>
        10
        <br />9<br />8<br />7<br />6
      </span>,
      <span>
        10
        <br />9<br />8<br />7<br />6<br />5
      </span>,
      <span>
        9<br />8<br />7<br />6<br />5
      </span>,
      <span>Nothing</span>,
    ],
    answer: (
      <span>
        10
        <br />9<br />8<br />7<br />6
      </span>
    ),
  },

  {
    question: (
      <div>
        <p>What characters appear?</p>
        <CodeBlock
          language="python"
          code={`name = "PYTHON"\nfor c in name:\n    print(c)`}
        />
      </div>
    ),
    options: [
      <span>PYTHON</span>,
      <span>P Y T H O N</span>,
      <span>
        P<br />Y<br />T<br />H<br />O<br />N
      </span>,
      <span>Error</span>,
    ],
    answer: (
      <span>
        P<br />Y<br />T<br />H<br />O<br />N
      </span>
    ),
  },

  {
    question: "What does range(5) generate?",
    options: [
      "0, 1, 2, 3, 4, 5",
      "1, 2, 3, 4, 5",
      "0, 1, 2, 3, 4",
      "5 numbers starting from 1",
    ],
    answer: "0, 1, 2, 3, 4",
  },

  {
    question: "In range(start, end), the end value is:",
    options: [
      "Included",
      "Not included",
      "Sometimes included",
      "Only included if step is 1",
    ],
    answer: "Not included",
  },

  {
    question: "Which of these correctly prints numbers from 5 to 9?",
    options: ["range(5, 10)", "range(5, 9)", "range(10)", "range(9, 5)"],
    answer: "range(5, 10)",
  },

  {
    question: "What kind of sequence does a for loop iterate over?",
    options: [
      "Only numbers",
      "Only strings",
      "Any sequence (string, range, etc.)",
      "Only lists",
    ],
    answer: "Any sequence (string, range, etc.)",
  },

  {
    question: "How do you loop through each character of the string 'ABC'?",
    options: [
      'for i in "ABC":',
      'for i in range("ABC"):',
      'for i in len("ABC"):',
      'for i in list("ABC"):',
    ],
    answer: 'for i in "ABC":',
  },
];

const ForLoop_MCQ = ({ subtopicId, goalName, courseName, onComplete }) => {
  const { markSubtopicComplete, loadProgressSummary, completedContent } =
    useAuth();

  const [isCompleted, setIsCompleted] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const randomQuestions = [...questionsData].sort(() => Math.random() - 0.5);

  // Check if subtopic is already completed
  useEffect(() => {
    if (subtopicId && completedContent.includes(subtopicId)) {
      setIsCompleted(true);
    }
  }, [completedContent, subtopicId]);

  const handleCompletion = async () => {
    if (isLoading || isCompleted) return;

    try {
      setIsLoading(true);

      // Validate that we have the required parameters
      if (!subtopicId) {
        console.error("❌ Subtopic ID is required");
        alert("Error: Subtopic ID is missing");
        return;
      }

      console.log("🎯 Marking subtopic complete:", {
        subtopicId,
        goalName,
        courseName,
      });

      const result = await markSubtopicComplete(
        subtopicId,
        goalName || "Goal 1",
        courseName || "Static Website: HTML CSS & Bootstrap"
      );

      if (result.success) {
        await loadProgressSummary();
        setIsCompleted(true);
        console.log("✅ MCQ successfully marked as completed");

        // Call the parent completion handler if provided
        if (onComplete) {
          onComplete();
        }
      } else {
        console.error("❌ Failed to mark MCQ complete:", result.message);
        alert(`Failed to mark as complete: ${result.message}`);
      }
    } catch (error) {
      console.error("❌ Failed to mark MCQ complete:", error);
      alert("Failed to mark as complete. Please try again.");
    } finally {
      setIsLoading(false);
    }
  };
  return (
    <MCQLogic
      title="For Loop - MCQs"
      questions={randomQuestions}
      isCompleted={isCompleted}
      isLoading={isLoading}
      onComplete={handleCompletion}
      subtopicId={subtopicId}
      goalName={goalName}
      courseName={courseName}
    />
  );
};

export default ForLoop_MCQ;
